package com.oolong.riddle_game.util

val testWords = listOf(
    "ability",
    "bike",
    "crowd",
    "dance",
    "economic",
    "farmer",
    "giant",
    "honest",
    "ice",
    "judgment",
    "key",
    "laboratory",
    "maintenance",
    "nervous",
    "object",
    "particular",
    "qualify",
    "reduction",
    "situation",
    "tear",
    "upper",
    "virus",
    "wander",
    "xenon",
    "year",
    "zone"
)